.PHONY: all 

all:
	gcc -Wall -O2  -I/export/homes/nidzwetzki/dsecondo/driver/cpp-driver/include -I/export/homes/nidzwetzki/dsecondo/driver/libuv/include -L/export/homes/nidzwetzki/dsecondo/driver/libuv/.libs -L/export/homes/nidzwetzki/dsecondo/driver/cpp-driver cql_paging.cpp -o cql_paging -luv -lcassandra
